/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a Stripe Checkout Session for the requested pack.
         *
         *     Returns the hosted Stripe URL. The browser navigates there; Stripe
         *     handles all card collection, 3DS, etc. On success/cancel, Stripe
         *     redirects back to `success_url` / `cancel_url` (configured here).
         *
         *     The webhook (NOT this endpoint) is what actually grants the credits.
         *     This endpoint just sets up the session.
         */
        post: operations["create_checkout_session_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Packs
         * @description Return every configured credit pack, cheapest first.
         *
         *     Public — no auth required. The catalog is fixed and not user-specific,
         *     and exposing it lets a future logged-out landing page show pricing.
         */
        get: operations["list_packs_billing_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Generations
         * @description List the caller's generations, newest first.
         */
        get: operations["list_generations_generations_get"];
        put?: never;
        /**
         * Create Generation
         * @description Submit a new generation. Returns immediately with status=pending.
         *
         *     The Celery worker picks up the row, charges credits, runs the provider,
         *     and lands it in done/failed. Clients poll `GET /generations/{id}` for
         *     updates.
         */
        post: operations["create_generation_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Generation
         * @description Fetch one generation. Returns 404 if it isn't the caller's row.
         */
        get: operations["get_generation_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Returns OK if the process is running.
         *
         *     Cheap — does not touch the database. Suitable for load-balancer
         *     liveness checks that fire every few seconds.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz Db
         * @description Readiness probe. Verifies the database is reachable by running SELECT 1.
         *
         *     More expensive than /healthz — actually hits the DB. Use for readiness
         *     checks that gate traffic, or as a smoke test during deploys.
         */
        get: operations["healthz_db_healthz_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's profile + credit balance.
         *
         *     Dev bypass: if the user's email matches `DEV_EMAIL`, the reported
         *     balance is effectively infinite. The actual `profiles.credit_balance`
         *     in the DB is unchanged — this is purely a read-time substitution so
         *     the dev never has to top up credits while developing.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return every enabled model the frontend can offer.
         */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List References
         * @description List the caller's references, newest first.
         */
        get: operations["list_references_references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign Reference Upload
         * @description Mint a signed PUT URL for the browser to upload directly to R2.
         */
        post: operations["presign_reference_upload_references_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references/{reference_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Reference
         * @description Delete the reference's R2 object and DB row.
         *
         *     Owner-scoped 404 (same pattern as /generations): we don't leak whether
         *     a foreign reference exists.
         */
        delete: operations["delete_reference_references__reference_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references/{reference_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Reference Upload
         * @description Verify the R2 upload and create the Reference row.
         *
         *     HEAD on R2 protects us from the client lying — without it a malicious
         *     user could call /complete without uploading and end up with a DB row
         *     pointing at nothing.
         *
         *     Also checks that the user_id in the R2 key matches the authenticated
         *     user — defense-in-depth: the key was minted by /presign with this user's
         *     ID, but if a key from another user's presign somehow leaks we still
         *     refuse to associate the row with the wrong user.
         */
        post: operations["complete_reference_upload_references__reference_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckoutRequest
         * @description POST /billing/checkout body.
         */
        CheckoutRequest: {
            /** Pack Id */
            pack_id: string;
        };
        /**
         * CheckoutResponse
         * @description The URL the browser should navigate to.
         */
        CheckoutResponse: {
            /** Checkout Url */
            checkout_url: string;
        };
        /**
         * CompleteRequest
         * @description Sent after the browser finishes the direct PUT.
         */
        CompleteRequest: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** Key */
            key: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * CreateGenerationRequest
         * @description Request body for POST /generations.
         */
        CreateGenerationRequest: {
            inputs: components["schemas"]["GenerationInput"];
            /**
             * Model Id
             * @description Must match a model returned by GET /models.
             */
            model_id: string;
        };
        /**
         * DBHealthResponse
         * @description Response shape for /healthz/db (readiness check including DB).
         */
        DBHealthResponse: {
            /** Db */
            db: string;
            /** Probe */
            probe: number;
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /**
         * GenerationInput
         * @description User-supplied inputs for a generation request.
         *
         *     Fields are all optional — which apply depends on the selected model's
         *     input_types. Validation that the right fields are present happens in
         *     the /generations endpoint.
         */
        GenerationInput: {
            /**
             * Image Urls
             * @default []
             */
            image_urls: string[];
            /** Text */
            text?: string | null;
        };
        /**
         * GenerationResponse
         * @description Public-facing shape of a Generation row.
         *
         *     Mirrors the DB columns we want to expose. Excludes user_id (already
         *     implicit via auth) and inputs (already in `prompt` for Sprint 3).
         */
        GenerationResponse: {
            /** Cost In Credits */
            cost_in_credits: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model Id */
            model_id: string;
            /** Prompt */
            prompt: string;
            /** Result Text */
            result_text: string | null;
            /** Result Url */
            result_url: string | null;
            status: components["schemas"]["GenerationStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GenerationStatus
         * @description Lifecycle of a generation row.
         *
         *     Stored as VARCHAR for the same reason TransactionType is — Alembic
         *     migrations of Postgres ENUMs are notoriously painful.
         * @enum {string}
         */
        GenerationStatus: "pending" | "processing" | "done" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response shape for /healthz (liveness check).
         */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /**
         * InputType
         * @description Kinds of input a model can accept.
         *
         *     Drives the dynamic form on the frontend: each entry in
         *     ModelConfig.input_types becomes a form field.
         * @enum {string}
         */
        InputType: "text" | "image" | "video";
        /**
         * MeResponse
         * @description Shape of GET /me.
         */
        MeResponse: {
            /** Balance */
            balance: number;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Name */
            name: string | null;
        };
        /**
         * ModelConfig
         * @description Frontend-visible metadata about one model.
         *
         *     Returned as a list from GET /models. The frontend uses this to:
         *       - populate the model dropdown (display_name)
         *       - render the right form fields (input_types)
         *       - display the cost (cost_in_credits)
         *       - decide whether to poll for an async result (is_async)
         */
        ModelConfig: {
            /** Cost In Credits */
            cost_in_credits: number;
            /** Display Name */
            display_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Input Types */
            input_types: components["schemas"]["InputType"][];
            /** Is Async */
            is_async: boolean;
            output_type: components["schemas"]["OutputType"];
            provider: components["schemas"]["ProviderName"];
        };
        /**
         * OutputType
         * @description Kind of output a model produces.
         * @enum {string}
         */
        OutputType: "text" | "image" | "video";
        /**
         * PackResponse
         * @description One credit pack as the frontend sees it.
         *
         *     Excludes the stripe_price_id because the browser never sends that —
         *     it sends `pack_id` (our slug) instead. Keeps the Stripe-side
         *     identifier out of the API contract.
         */
        PackResponse: {
            /** Credits */
            credits: number;
            /** Currency */
            currency: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Price Cents */
            price_cents: number;
        };
        /**
         * PresignRequest
         * @description What the browser sends to /references/presign before uploading.
         */
        PresignRequest: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * PresignResponse
         * @description Everything the browser needs to perform the direct PUT to R2.
         */
        PresignResponse: {
            /** Content Type */
            content_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Key */
            key: string;
            /** Public Url */
            public_url: string;
            /**
             * Reference Id
             * Format: uuid
             */
            reference_id: string;
            /** Size Bytes */
            size_bytes: number;
            /** Upload Url */
            upload_url: string;
        };
        /**
         * ProviderName
         * @description The AI services we can route to.
         * @enum {string}
         */
        ProviderName: "google-ai-studio" | "vertex-ai" | "sjinn" | "pollinations" | "cloudflare-workers-ai" | "seegen";
        /**
         * ReferenceResponse
         * @description Public-facing shape of a Reference row.
         */
        ReferenceResponse: {
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Public Url */
            public_url: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_checkout_session_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packs_billing_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackResponse"][];
                };
            };
        };
    };
    list_generations_generations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthz_db_healthz_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DBHealthResponse"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfig"][];
                };
            };
        };
    };
    list_references_references_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_reference_upload_references_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reference_references__reference_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_reference_upload_references__reference_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
