"""add_references_table

Revision ID: 352086a915a3
Revises: 2724c5210cfe
Create Date: 2026-05-22 00:06:20.665253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel models use sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '352086a915a3'
down_revision: Union[str, Sequence[str], None] = '2724c5210cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_created_at'), 'references', ['created_at'], unique=False)
    op.create_index(op.f('ix_references_user_id'), 'references', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_user_id'), table_name='references')
    op.drop_index(op.f('ix_references_created_at'), table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###
