"""generations_provider_job_id

Revision ID: 6dbabf5d486a
Revises: a1e63fecb42b
Create Date: 2026-05-24 21:39:59.534964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel models use sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '6dbabf5d486a'
down_revision: Union[str, Sequence[str], None] = 'a1e63fecb42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('provider_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_generations_provider_job_id'), 'generations', ['provider_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_provider_job_id'), table_name='generations')
    op.drop_column('generations', 'provider_job_id')
    # ### end Alembic commands ###
